leagues:
  2: UEFA Champions League
  3: UEFA Europa League
  4: Euro Championship
  6: Africa Cup of Nations
  8: World Cup - Women
  10: Friendlies
  11: CONMEBOL Sudamericana
  13: CONMEBOL Libertadores
  15: FIFA Club World Cup
  16: CONCACAF Champions League
  22: CONCACAF Gold Cup
  36: Africa Cup of Nations Qualification
  38: UEFA U21 Championship
  39: Premier League
  40: Championship
  45: FA Cup
  61: Ligue 1
  62: Ligue 2
  64: Feminine Division 1
  66: Coupe de France
  71: Serie A (Brazil)
  78: Bundesliga
  79: 2. Bundesliga
  81: DFB Pokal
  88: Eredivisie
  94: Primeira Liga (Portugal)
  103: Eliteserien (Norway)
  106: Ekstraklasa (Poland)
  110: Premier (Wales)
  113: Allsvenskan (Sweden)
  119: Superligaen (Denmark)
  135: Serie A
  136: Serie B
  137: Coppa Italia
  140: La Liga
  141: "Segunda Divisi\xF3n"
  144: Jupiler Pro League
  164: Premier (Iceland)
  172: A PFG (Bulgaria)
  179: Premiership (Scotland)
  186: Ligue 1 (Algeria)
  197: Super League (Switzerland/Greece)
  203: Super Lig (Turkey)
  210: Prva HNL (Croatia)
  218: Tipp3 Bundesliga (Austria)
  239: Primera A (Colombia)
  242: Serie A (Ecuador)
  244: Veikkausliiga (Finland)
  250: Primera Division - Apertura (Paraguay)
  252: Primera Division - Clausura (Paraguay)
  253: Major League Soccer
  261: National Division (Luxembourg)
  262: Liga MX
  265: Primera Division (Chile)
  271: NB I (Hungary)
  283: Liga I (Romania)
  286: Super Liga (Serbia)
  315: Premijer Liga (Bosnia)
  327: Erovnuli Liga (Georgia)
  329: Meistriliiga (Estonia)
  332: Super Liga (Slovakia)
  333: Premier League (Ukraine)
  345: Czech Liga
  355: First League (Montenegro)
  357: Premier Division (Ireland)
  362: A Lyga (Lithuania)
  365: Virsliga (Latvia)
  373: 1. SNL (Slovenia)
  394: "Divizia Na\u021Bional\u0103 (Moldova)"
  408: Premiership (Northern Ireland)
  525: UEFA Champions League Women
  528: Community Shield
  529: Super Cup (Germany)
  531: UEFA Super Cup
  541: CONMEBOL Recopa
  556: Super Cup (Spain)
  666: Friendlies Women
  743: UEFA Championship - Women
  772: Leagues Cup
  848: UEFA Europa Conference League
  850: UEFA U21 Championship - Qualification
  858: CONCACAF Gold Cup - Qualification
  1040: UEFA Nations League - Women
  1083: UEFA Championship - Women - Qualification
  1186: FIFA Club World Cup - Play-In
